### ISSUE TITLE
cross-compiling and microphone

### ISSUE THREAD

**Issue by rshmelev** [timshannon/go-openal#5]
Hi Tim,
As I understand, OpenAL supports reading from microphone and it is quite cool.
The question is - can i cross-compile my app (which is using your libarary) on my Mac?
So i'll get 3 binaries, for Windows, Linux, Mac...

**Comment by timshannon** [comment]
Although I haven't personally tried it you should be able to setup a cross compile environment with the openAL library.  There are build-tags for darwing in https://github.com/timshannon/go-openal/blob/master/openal/core.go  and I believe others have built fine on a mac.
